# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: RESTEasy MicroProfile Integration Tests

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.gitignore'
      - ".mvn"
      - "CODEOWNERS"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.adoc"
      - "dco.txt"
      - "LICENSE"
      - "mvnw"
      - "mvnw.cmd"
      - "README.adoc"
      - "security.txt"
      - "*/README.adoc"
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

jobs:
  resteasy-test:
    name: Build and test against RESTEasy
    outputs:
      wildfly-version: ${{steps.version.outputs.resteasy-version}}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ '11', '17' ]

    steps:
      - name: Checkout RESTEasy MicroProfile
        uses: actions/checkout@v3
        with:
          path: resteasy-microprofile
      - name: Checkout RESTEasy
        uses: actions/checkout@v3
        with:
          repository: resteasy/resteasy
          path: resteasy
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build RESTEasy Java ${{ matrix.java }} - ${{ matrix.os }}
        id: build-resteasy
        run: |
          cd resteasy
          mvn clean install -B -Denforcer.skip=true -Dcheckstyle.skip=true -DskipTests
          echo "RESTEASY_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Build and Test RESTEasy MicroProfile Java ${{ matrix.java }} - ${{ matrix.os }}
        run: |
          cd resteasy-microprofile
          mvn clean install -B -Denforcer.skip=true -Dcheckstyle.skip=true -DskipTests
          echo "RESTEASY_VERSION=${{ steps.build-resteasy.outputs.RESTEASY_VERSION }}"
          mvn verify -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dskip.compile=true -Dversion.org.jboss.resteasy=${{ steps.build-resteasy.outputs.RESTEASY_VERSION }} \
            -pl config,context-propagation,rest-client,testsuite/integration-tests,testsuite/microprofile-rest-client-tck \
            -Dversion.jakarta.servlet=6.0.0
          -Pci
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'

  wildfly-test:
    name: Build and test against WildFly
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        java: [ '11', '17' ]
        profile:
          - ''
          - "'-Dprovision.preview'"
    steps:
      - name: Checkout RESTEasy MicroProfile
        uses: actions/checkout@v3
        with:
          path: resteasy-microprofile
      - name: Checkout RESTEasy
        uses: actions/checkout@v3
        with:
          repository: wildfly/wildfly
          path: wildfly
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build WildFly Java ${{ matrix.java }} - ${{ matrix.os }}
        id: build-wildfly
        run: |
          cd wildfly
          mvn clean install -B -Denforcer.skip=true -Dcheckstyle.skip=true -DskipTests
          echo "WILDFLY_VERSION=$(mvn help:evaluate -Dversion.help.plugin=3.2.0 -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Build and Test RESTEasy MicroProfile Java ${{ matrix.java }} - ${{ matrix.os }}
        run: |
          cd resteasy-microprofile
          mvn clean install -B -Denforcer.skip=true -Dcheckstyle.skip=true -DskipTests
          echo "WILDFLY_VERSION=${{ steps.build-wildfly.outputs.WILDFLY_VERSION }}"
          mvn verify -B -Denforcer.skip=true -Dcheckstyle.skip=true -Dskip.compile=true -Dversion.org.wildfly=${{ steps.build-wildfly.outputs.WILDFLY_VERSION }} \
            -pl testsuite/integration-tests,testsuite/microprofile-rest-client-tck -Pci ${{ matrix.profile }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}
          path: '**/surefire-reports/*.txt'

